// Code generated by go-swagger; DO NOT EDIT.

// Package restapi traefik-api-key-forward-auth
//
//	API key-based authenticator for Traefik.
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
