// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mentatxx/traefik-api-key-forward-auth/models"
)

// AddKeyHandlerFunc turns a function with the right signature into a add key handler
type AddKeyHandlerFunc func(AddKeyParams, *models.AuthPrincipal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddKeyHandlerFunc) Handle(params AddKeyParams, principal *models.AuthPrincipal) middleware.Responder {
	return fn(params, principal)
}

// AddKeyHandler interface for that can handle valid add key params
type AddKeyHandler interface {
	Handle(AddKeyParams, *models.AuthPrincipal) middleware.Responder
}

// NewAddKey creates a new http.Handler for the add key operation
func NewAddKey(ctx *middleware.Context, handler AddKeyHandler) *AddKey {
	return &AddKey{Context: ctx, Handler: handler}
}

/*
	AddKey swagger:route POST /key key addKey

Add a new API key
*/
type AddKey struct {
	Context *middleware.Context
	Handler AddKeyHandler
}

func (o *AddKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddKeyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthPrincipal
	if uprinc != nil {
		principal = uprinc.(*models.AuthPrincipal) // this is really a models.AuthPrincipal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
