// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mentatxx/traefik-api-key-forward-auth/models"
)

// AddKeyOKCode is the HTTP code returned for type AddKeyOK
const AddKeyOKCode int = 200

/*
AddKeyOK successful operation

swagger:response addKeyOK
*/
type AddKeyOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreateKeyResult `json:"body,omitempty"`
}

// NewAddKeyOK creates AddKeyOK with default headers values
func NewAddKeyOK() *AddKeyOK {

	return &AddKeyOK{}
}

// WithPayload adds the payload to the add key o k response
func (o *AddKeyOK) WithPayload(payload *models.CreateKeyResult) *AddKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add key o k response
func (o *AddKeyOK) SetPayload(payload *models.CreateKeyResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddKeyBadRequestCode is the HTTP code returned for type AddKeyBadRequest
const AddKeyBadRequestCode int = 400

/*
AddKeyBadRequest Invalid input

swagger:response addKeyBadRequest
*/
type AddKeyBadRequest struct {
}

// NewAddKeyBadRequest creates AddKeyBadRequest with default headers values
func NewAddKeyBadRequest() *AddKeyBadRequest {

	return &AddKeyBadRequest{}
}

// WriteResponse to the client
func (o *AddKeyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddKeyUnauthorizedCode is the HTTP code returned for type AddKeyUnauthorized
const AddKeyUnauthorizedCode int = 401

/*
AddKeyUnauthorized Unauthenticated

swagger:response addKeyUnauthorized
*/
type AddKeyUnauthorized struct {
}

// NewAddKeyUnauthorized creates AddKeyUnauthorized with default headers values
func NewAddKeyUnauthorized() *AddKeyUnauthorized {

	return &AddKeyUnauthorized{}
}

// WriteResponse to the client
func (o *AddKeyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
