// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mentatxx/traefik-api-key-forward-auth/models"
)

// GetKeysOKCode is the HTTP code returned for type GetKeysOK
const GetKeysOKCode int = 200

/*
GetKeysOK successful operation

swagger:response getKeysOK
*/
type GetKeysOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetKeysResult `json:"body,omitempty"`
}

// NewGetKeysOK creates GetKeysOK with default headers values
func NewGetKeysOK() *GetKeysOK {

	return &GetKeysOK{}
}

// WithPayload adds the payload to the get keys o k response
func (o *GetKeysOK) WithPayload(payload *models.GetKeysResult) *GetKeysOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get keys o k response
func (o *GetKeysOK) SetPayload(payload *models.GetKeysResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKeysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetKeysBadRequestCode is the HTTP code returned for type GetKeysBadRequest
const GetKeysBadRequestCode int = 400

/*
GetKeysBadRequest Invalid request supplied

swagger:response getKeysBadRequest
*/
type GetKeysBadRequest struct {
}

// NewGetKeysBadRequest creates GetKeysBadRequest with default headers values
func NewGetKeysBadRequest() *GetKeysBadRequest {

	return &GetKeysBadRequest{}
}

// WriteResponse to the client
func (o *GetKeysBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
