// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateKeyBody create key body
//
// swagger:model CreateKeyBody
type CreateKeyBody struct {

	// Custom attributes (optional)
	Attributes interface{} `json:"attributes,omitempty"`

	// Organization ID (optional)
	OrganizationID string `json:"organizationId,omitempty"`

	// Project ID (optional)
	ProjectID string `json:"projectId,omitempty"`

	// User ID (optional)
	UserID string `json:"userId,omitempty"`
}

// Validate validates this create key body
func (m *CreateKeyBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create key body based on context it is used
func (m *CreateKeyBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateKeyBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateKeyBody) UnmarshalBinary(b []byte) error {
	var res CreateKeyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
