// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateKey create key
//
// swagger:model CreateKey
type CreateKey struct {

	// Custom attributes (optional)
	Attributes interface{} `json:"attributes,omitempty"`

	// Organization ID (optional)
	OrganizationID string `json:"organizationId,omitempty"`

	// Project ID (optional)
	ProjectID string `json:"projectId,omitempty"`

	// User ID (optional)
	UserID string `json:"userId,omitempty"`
}

// Validate validates this create key
func (m *CreateKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create key based on context it is used
func (m *CreateKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateKey) UnmarshalBinary(b []byte) error {
	var res CreateKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
